apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-sim
  labels:
    app: manu-sensor-sim
    app.kubernetes.io/part-of: manu-sensor-sim
spec:
  selector:
    matchLabels:
      app: sensor-sim
  replicas: 1
  template:
    metadata:
      labels:
        app: sensor-sim
    spec:
      containers:
        - name: sensor-sim
          image: quay.io/sbergste/tb-sensor-sim:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: sensor-sim-conf
      restartPolicy: Always
